FORMAT: 1A
HOST: https://localhost:5000/

# Fungus among us 

An API to faciliate communication between a front end application and a classifier neural network.

## Classification [/questions]

###  Classify an image [POST]

+ Response 200 (application/json)

        [
            {
              "name": "foo",
              "predictions": {
                "Class 1" : "prediction 1",
                "Class 2" : "prediction 2",
                "Class N" : "prediction N"
              }
            }
        ]