image:
  width: 256
  height: 256
  channels: 1
server:
  host: localhost
  port: 5000
  debug: True
classification:
  classes:
    - Agaricus
    - Amanita
    - Boletus
    - Cortinarius
    - Entoloma
    - Hygrocybe
    - Lactarius
    - Russula
    - Suillus
  model: ../model/model
  upload_folder: ../data/upload
training:
  test_data: ../data/image-dataset/mushrooms/test
  train_data: ../data/image-dataset/mushrooms/train
  keys:
    kaggle: ./keychain/kaggle